exports.modules =  {
    code: "0",
    msg: "查询成功!",
    version: "1",
    data: [
        {
            bean: {
                name: "绍兴市交通运输局",
                contact: null,
                mobilenumber: null,
                addr: null,
                categoryId: 0,
                organType: null,
                remark: null,
                provinceId: null,
                cityId: null,
                netCode: null,
                qrCodeId: null,
                areaId: null,
                mfhArea: null,
                mfhCity: null,
                longitude: null,
                latitude: null,
                additional: null,
                innerDel: 0,
                ownerId: null,
                gaoId: null,
                status: 0,
                ability: 0,
                tenantId: -1,
                saasId: 134342,
                stockId: null,
                id: 1,
                createdBy: "",
                createdDate: null,
                updatedBy: "",
                updatedDate: "2017-02-25 14:55:43"
            },
            caption: {
                tenantId: "无上级部门",
                status: "无效账号"
            }
        },
        {
            bean: {
                name: "绍兴市道路运输管理局",
                contact: null,
                mobilenumber: null,
                addr: null,
                categoryId: 0,
                organType: null,
                remark: null,
                provinceId: null,
                cityId: null,
                netCode: null,
                qrCodeId: null,
                areaId: null,
                mfhArea: null,
                mfhCity: null,
                longitude: null,
                latitude: null,
                additional: null,
                innerDel: 0,
                ownerId: null,
                gaoId: null,
                status: 1,
                ability: 0,
                tenantId: 1,
                saasId: 134342,
                stockId: null,
                id: 2,
                createdBy: "",
                createdDate: null,
                updatedBy: "",
                updatedDate: "2017-02-25 13:50:34"
            },
            caption: {
                tenantId: "绍兴市交通运输局",
                status: "有效账号"
            }
        },
        {
            bean: {
                name: "绍兴市公路局",
                contact: null,
                mobilenumber: null,
                addr: null,
                categoryId: 0,
                organType: null,
                remark: null,
                provinceId: null,
                cityId: null,
                netCode: null,
                qrCodeId: null,
                areaId: null,
                mfhArea: null,
                mfhCity: null,
                longitude: null,
                latitude: null,
                additional: null,
                innerDel: 0,
                ownerId: null,
                gaoId: null,
                status: 1,
                ability: 0,
                tenantId: 1,
                saasId: 134342,
                stockId: null,
                id: 3,
                createdBy: "",
                createdDate: null,
                updatedBy: "",
                updatedDate: "2017-02-25 14:29:00"
            },
            caption: {
                tenantId: "绍兴市交通运输局",
                status: "有效账号"
            }
        },
        {
            bean: {
                name: "绍兴市港航局222",
                contact: "联系人",
                mobilenumber: "联系人手机号",
                addr: "地址",
                categoryId: null,
                organType: null,
                remark: "备注",
                provinceId: null,
                cityId: null,
                netCode: null,
                qrCodeId: null,
                areaId: null,
                mfhArea: null,
                mfhCity: null,
                longitude: 120.221,
                latitude: 30.232,
                additional: null,
                innerDel: null,
                ownerId: null,
                gaoId: null,
                status: 1,
                ability: null,
                tenantId: 1,
                saasId: 1,
                stockId: null,
                id: 9,
                createdBy: "1",
                createdDate: "2017-02-25 14:47:05",
                updatedBy: "",
                updatedDate: "2017-02-25 14:53:41"
            },
            caption: {
                tenantId: "绍兴市交通运输局",
                status: "有效账号"
            }
        }
    ]
}