modules = [
    {
        user: {
            userName: "gdy",
            userCaption: "哥达鸭",
            phonenumber: null,
            wxopenid: null,
            qq: null,
            email: "",
            password: "",
            token: null,
            salt: null,
            status: 1,
            userType: 1,
            humanId: 15,
            tenantId: 1,
            saasId: null,
            id: null,
            createdBy: "",
            createdDate: "2017-02-15 10:34:20",
            updatedBy: "",
            updatedDate: "2017-02-15 10:34:18"
        },
        name: "哥达鸭",
        idCard: "3301021999900000000",
        sex: 0,
        marriage: 1,
        nationality: null,
        wechatId: "微信号",
        birthPlace: null,
        birthday: "2015-09-01 00:00:00",
        religion: null,
        party: "党员",
        address: "家庭住址",
        zipcode: "邮编",
        phone: "座机号",
        mobile: "18888888888",
        qq: null,
        email: "邮箱",
        eduMajor: "专业",
        eduDegree: "学历",
        eduCollege: "毕业院校",
        eduCase: "教育背景",
        startWorkDate: null,
        workCase: null,
        hobby: "爱好",
        remark: "备注",
        type: null,
        status: 1,
        auth: null,
        authFlag: null,
        saasId: null,
        id: 15,
        createdBy: "1",
        createdDate: "2017-02-15 10:33:55",
        updatedBy: "1",
        updatedDate: null
    },
    {
        user: {
            userName: "爸爸吧",
            userCaption: "哥达鸭",
            phonenumber: null,
            wxopenid: null,
            qq: null,
            email: "",
            password: "",
            token: null,
            salt: null,
            status: null,
            userType: 1,
            humanId: 18,
            tenantId: 1,
            saasId: null,
            id: null,
            createdBy: "",
            createdDate: "2017-02-16 15:44:55",
            updatedBy: "",
            updatedDate: "2017-02-16 15:44:55"
        },
        name: "哥达鸭",
        idCard: "3301021999900000000",
        sex: 0,
        marriage: 1,
        nationality: null,
        wechatId: "微信号",
        birthPlace: null,
        birthday: "2015-09-01 00:00:00",
        religion: null,
        party: "党员",
        address: "家庭住址",
        zipcode: "邮编",
        phone: "座机号",
        mobile: "手机号",
        qq: null,
        email: "邮箱",
        eduMajor: "专业",
        eduDegree: "学历",
        eduCollege: "毕业院校",
        eduCase: "教育背景",
        startWorkDate: null,
        workCase: null,
        hobby: "爱好",
        remark: "备注",
        type: null,
        status: null,
        auth: null,
        authFlag: null,
        saasId: null,
        id: 18,
        createdBy: "-1",
        createdDate: "2017-02-16 15:44:55",
        updatedBy: "-1",
        updatedDate: null
    }
];
